# Generated by Django 6.0.6 on 2026-07-09 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_producto_proveedor'),
        ('ventas', '0002_cuadrar_total_con_tarjeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('precio_original__gte', 0)), name='detalle_precio_original_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='detalle_precio_unitario_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='detalle_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__lte', models.F('precio_original'))), name='detalle_precio_descuento_lte_original'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='venta_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='venta_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_aplicado__gte', 0)), name='venta_saldo_aplicado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_total__gte', 0)), name='venta_descuento_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('monto_tarjeta__isnull', True), ('monto_tarjeta__gte', 0), _connector='OR'), name='venta_monto_tarjeta_no_negativo'),
        ),
    ]
