# Generated by Django 6.0.6 on 2026-07-07 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartados', '0001_initial'),
        ('clientes', '0001_initial'),
        ('productos', '0002_producto_proveedor'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apartado',
            index=models.Index(fields=['estado'], name='apartados_a_estado_4f66c1_idx'),
        ),
        migrations.AddIndex(
            model_name='apartado',
            index=models.Index(fields=['-creado'], name='apartados_a_creado_243bce_idx'),
        ),
    ]
