# Generated by Django 6.0.6 on 2026-07-09 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartados', '0002_apartado_apartados_a_estado_4f66c1_idx_and_more'),
        ('clientes', '0001_initial'),
        ('productos', '0002_producto_proveedor'),
        ('ventas', '0002_cuadrar_total_con_tarjeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='abono',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='abono_monto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apartado',
            constraint=models.CheckConstraint(condition=models.Q(('precio_original__gte', 0)), name='apartado_precio_original_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apartado',
            constraint=models.CheckConstraint(condition=models.Q(('precio_total__gte', 0)), name='apartado_precio_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apartado',
            constraint=models.CheckConstraint(condition=models.Q(('precio_total__lte', models.F('precio_original'))), name='apartado_precio_total_lte_original'),
        ),
    ]
