# Generated by Django 6.0.6 on 2026-07-04 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anulacion', 'Anulación'), ('producto', 'Producto'), ('descuento', 'Descuento'), ('saldo', 'Saldo'), ('apartado', 'Apartado'), ('sesion', 'Sesión'), ('usuario', 'Usuario')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de actividad',
                'verbose_name_plural': 'registros de actividad',
                'ordering': ('-creado',),
                'indexes': [models.Index(fields=['tipo'], name='usuarios_re_tipo_84a85d_idx'), models.Index(fields=['-creado'], name='usuarios_re_creado_c1e033_idx')],
            },
        ),
    ]
