# Generated by Django 6.0.6 on 2026-07-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_registroactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='tipo',
            field=models.CharField(choices=[('anulacion', 'Anulación'), ('producto', 'Producto'), ('cliente', 'Cliente'), ('descuento', 'Descuento'), ('saldo', 'Saldo'), ('apartado', 'Apartado'), ('sesion', 'Sesión'), ('usuario', 'Usuario')], max_length=20),
        ),
    ]
