# Generated by Django 6.0.6 on 2026-07-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('saldo_favor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo a favor')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('nombre',),
            },
        ),
    ]
