# Generated by Django 6.0.6 on 2026-07-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre del contacto')),
                ('empresa', models.CharField(max_length=150, verbose_name='empresa')),
                ('telefono', models.CharField(max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ('empresa',),
            },
        ),
    ]
